script:
  ############################################################################
  #                                                                          #
  #   Update Zigbee2mqtt Containers                                          #
  #                                                                          #
  ############################################################################

  # Living Room
  update_z2m_living_room_container:
    alias: "Update Zigbee2mqtt Living Room Container"
    use_blueprint:
      path: update_dockhand_container.yaml
      input:
        container_name: zigbee2mqtt
        env: 3

  # Floor 2
  update_z2m_floor_2_container:
    alias: "Update Zigbee2mqtt Floor 2 Container"
    use_blueprint:
      path: update_dockhand_container.yaml
      input:
        container_name: zigbee2mqtt
        env: 2

  # Basement
  update_z2m_basement_container:
    alias: "Update Zigbee2mqtt Basement Container"
    use_blueprint:
      path: update_dockhand_container.yaml
      input:
        container_name: z2m_basement
        env: 1
